TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'paragraph', nesting: 1, level: 1, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'I\'m looking forward.',
       level: 2,
       parent: [Object] },
     { type: 'hardbreak', nesting: 0, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'foo "foo \'inside\' bar" bar',
       level: 2,
       parent: [Object] },
     { type: 'hardbreak', nesting: 0, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'My sisters\' friends\' investments',
       level: 2,
       parent: [Object] },
     { type: 'hardbreak', nesting: 0, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: '(c) 2017 Alexander Schilling',
       level: 2,
       parent: [Object] },
     { type: 'hardbreak', nesting: 0, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: '2013 Intel (R); 2013 Intel (TM)',
       level: 2,
       parent: [Object] },
     { type: 'hardbreak', nesting: 0, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Tickets cost 20 usd in Australia or 19 EUR in Germany',
       level: 2,
       parent: [Object] },
     { type: 'hardbreak', nesting: 0, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'foo...bar',
       level: 2,
       parent: [Object] },
     { type: 'hardbreak', nesting: 0, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'foo -- bar and foo — bar',
       level: 2,
       parent: [Object] },
     { type: 'hardbreak', nesting: 0, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Kurt Cobain (1967-1994)',
       level: 2,
       parent: [Object] },
     { type: 'hardbreak', nesting: 0, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: '1 <- 2 -> 3 <-> 4 <= 5 => 6 <=> 7',
       level: 2,
       parent: [Object] },
     { type: 'hardbreak', nesting: 0, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: '2 x 3 = 6; 3 - 2 = 1; 3 =< 2; 4 >= 4; 5 +- 1; 10 -+ 1; 2 << 100; 999 >> 5',
       level: 2,
       parent: [Object] },
     { type: 'hardbreak', nesting: 0, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'foo  bar; foo.  Bar; foo,  bar',
       level: 2,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 1, parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 26,
  token: 
   { type: 'paragraph',
     nesting: -1,
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }