language: node_js
node_js:
   - "0.10"
   - "0.12"
   - "4"
after_success:
   - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=cXdE3VQURu56kmSmDh69N1J1aIDXzNhj9 node_modules/.bin/builder -c test --coverage --coveralls