# Default settings for Report
# ============================================
# This contains the default for different settings.

format:


  # Markdown Format
  # --------------------------------------------
  md:
    type: md
    width: 100

  text:
    type: text
    width: 100
    ascii_art: true

  console:
    type: text
    width: 100
    ascii_art: true

  html:
    type: html
    compress: false

  man:
    type: roff
