# Default settings for Report
# ============================================
# This contains the default for different settings.

format:


  # Markdown Format
  # --------------------------------------------
  md:
    type: md
    width: 100

  html:
    type: html
    
