# Default settings for Report
# ============================================
# This contains the default for different settings.

format:


  # Markdown Format
  # --------------------------------------------
  md:
    type: md
    width: 100
    extension: '.md'

  text:
    type: text
    width: 100
    ascii_art: true
    extension: '.txt'

  console:
    type: text
    width: 100
    ascii_art: true
    extension: '.console'

  html:
    type: html
    compress: false
    extension: '.html'

  man:
    type: roff
    extension: '.man'

  latex:
    type: latex
    extension: '.latex'

  pdf:
    type: latex
    convert:
      type: pdf
    extension: '.pdf'

  rtf:
    type: rtf
    extension: '.rtf'
