# Default settings for Report Formats
# ============================================
# This contains the default for different settings.


# Markdown Format
# --------------------------------------------
md:
  type: md
  extension: '.md'
  width: 100
  keep_soft_breaks: true
  use_references: true

text:
  type: text
  extension: .txt
  width: 100
  ascii_art: true
  ansi_escape: false

console:
  type: text
  extension: .console
  width: 100
  ascii_art: true
  ansi_escape: true

html:
  type: html
  extension: .html
  compress: false
  head_end: <meta name="generator" content="alinex-report" /></html>
  body_begin: <body><div id="page">
  body_end: </div></body>

man:
  type: roff
  extension: .man

adoc:
  type: adoc
  extension: .adoc

latex:
  type: latex
  extension: .latex

pdf:
  type: latex
  convert:
    type: pdf
  extension: .pdf

rtf:
  type: rtf
  extension: .rtf
