# Default settings for Report Formats
# ============================================
# This contains the default for different settings.


# Markdown Format
# --------------------------------------------
md:
  type: md
  extension: '.md'
  width: 100
  keep_soft_breaks: true
  use_references: true

text:
  type: text
  extension: .txt
  width: 100
  ascii_art: true
  ansi_escape: false

console:
  type: text
  extension: .console
  width: 100
  ascii_art: true
  ansi_escape: true

html:
  type: html
  extension: .html
  compress: false
  head_begin: <!DOCTYPE html><html><head>
  head_end: |+
    <meta name="generator" content="alinex-report" />
    <meta charset="UTF-8" />
    </head>
  body_begin: <body><div id="page">
  body_end: </div></body>
  style:
    - report/default.css

html2png:
  type: html
  extension: .html.png
  convert:
    type: png
    width: 800
    height: 600
    capture: '#page'

man:
  type: roff
  extension: .man

adoc:
  type: adoc
  extension: .adoc

latex:
  type: latex
  extension: .latex

pdf:
  type: latex
  convert:
    type: pdf
  extension: .pdf

rtf:
  type: rtf
  extension: .rtf
