TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'paragraph', nesting: 1, level: 1, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'It\'s an ',
       level: 2,
       parent: [Object] },
     { type: 'image',
       nesting: 1,
       src: 'http://alinex.github.io/images/Alinex-200.png',
       title: 'my logo',
       level: 2,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'alinex',
       level: 3,
       parent: [Object] },
     { type: 'image',
       nesting: -1,
       src: 'http://alinex.github.io/images/Alinex-200.png',
       title: 'my logo',
       level: 2,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: ' project.',
       level: 2,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 1, parent: [Object] },
     { type: 'style',
       nesting: 0,
       format: 'html',
       block: true,
       content: 'width=100',
       level: 1,
       parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 9,
  token: 
   { type: 'style',
     nesting: 0,
     format: 'html',
     block: true,
     content: 'width=100',
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }