TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'paragraph', nesting: 1, level: 1, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Red text',
       level: 2,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 1, parent: [Object] },
     { type: 'style',
       nesting: 0,
       format: 'html',
       block: true,
       content: '.text-red',
       level: 1,
       parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 5,
  token: 
   { type: 'style',
     nesting: 0,
     format: 'html',
     block: true,
     content: '.text-red',
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }