TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'raw',
       nesting: 0,
       format: 'html',
       block: true,
       content: '<form>',
       level: 1,
       parent: [Object] },
     { type: 'paragraph', nesting: 1, level: 1, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Some ',
       level: 2,
       parent: [Object] },
     { type: 'raw',
       nesting: 0,
       format: 'html',
       block: false,
       content: '<input type="text" />',
       level: 2,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: ' input.',
       level: 2,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 1, parent: [Object] },
     { type: 'raw',
       nesting: 0,
       format: 'html',
       block: true,
       content: '</form>',
       level: 1,
       parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 8,
  token: 
   { type: 'raw',
     nesting: 0,
     format: 'html',
     block: true,
     content: '</form>',
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }