TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'raw',
       nesting: 0,
       format: 'html',
       block: true,
       content: '<div class="important">',
       level: 1,
       parent: [Object] },
     { type: 'paragraph', nesting: 1, level: 1, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Some ',
       level: 2,
       parent: [Object] },
     { type: 'raw',
       nesting: 0,
       format: 'html',
       block: false,
       content: '<a class="red">',
       level: 2,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'inline',
       level: 2,
       parent: [Object] },
     { type: 'raw',
       nesting: 0,
       format: 'html',
       block: false,
       content: '</a>',
       level: 2,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: ' html.',
       level: 2,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 1, parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 9,
  token: 
   { type: 'paragraph',
     nesting: -1,
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }