@startuml

start
partition "Create Report" {
    fork
      :Parser|
      :Pre Optimize;
      :Transform;
      :Token List]
      :Post Format;
    fork again
      :Builder|
      :API Calls;
      if (has text?) then (yes)
        :Parser|
      else (no)
        :Create Token;
      endif
    end fork
    :Token Tree]
}
partition "Output Report" {
  :Formatter|
  :select format;
  note right
    - html
    - console
    - text
    - markdown
  end note
  :pre optimize;
  :transform format;
  :post optimize;
  :join into stream;
  :Text]
  :convert;
  :Output]
}
stop

@enduml
