TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'paragraph', nesting: 1, level: 1, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Let\'s ',
       level: 2,
       parent: [Object] },
     { type: 'link',
       nesting: 1,
       href: 'http://www.google.com',
       title: 'search engine',
       level: 2,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'google',
       level: 3,
       parent: [Object] },
     { type: 'link', nesting: -1, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: ' for everything you don\'t know.',
       level: 2,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 1, parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 8,
  token: 
   { type: 'paragraph',
     nesting: -1,
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }