TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'paragraph', nesting: 1, level: 1, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'To shut a debian system down enter ',
       level: 2,
       parent: [Object] },
     { type: 'fixed', nesting: 1, level: 2, parent: [Object] },
     { type: 'text',
       content: 'shutdown -h now',
       level: 3,
       parent: [Object] },
     { type: 'fixed', nesting: -1, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: ' in a console as ',
       level: 2,
       parent: [Object] },
     { type: 'fixed', nesting: 1, level: 2, parent: [Object] },
     { type: 'text', content: 'root', level: 3, parent: [Object] },
     { type: 'fixed', nesting: -1, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: '.',
       level: 2,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 1, parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 12,
  token: 
   { type: 'paragraph',
     nesting: -1,
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }