TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'paragraph', nesting: 1, level: 1, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Only italic ',
       level: 2,
       parent: [Object] },
     { type: 'emphasis', nesting: 1, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'here',
       level: 3,
       parent: [Object] },
     { type: 'emphasis', nesting: -1, level: 2, parent: [Object] },
     { type: 'hardbreak', nesting: 0, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Only strong ',
       level: 2,
       parent: [Object] },
     { type: 'strong', nesting: 1, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'here',
       level: 3,
       parent: [Object] },
     { type: 'strong', nesting: -1, level: 2, parent: [Object] },
     { type: 'hardbreak', nesting: 0, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'And both ',
       level: 2,
       parent: [Object] },
     { type: 'strong', nesting: 1, level: 2, parent: [Object] },
     { type: 'emphasis', nesting: 1, level: 3, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'here',
       level: 4,
       parent: [Object] },
     { type: 'emphasis', nesting: -1, level: 3, parent: [Object] },
     { type: 'strong', nesting: -1, level: 2, parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 1, parent: [Object] },
     { type: 'paragraph', nesting: 1, level: 1, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'You ',
       level: 2,
       parent: [Object] },
     { type: 'emphasis', nesting: 1, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'can ',
       level: 3,
       parent: [Object] },
     { type: 'strong', nesting: 1, level: 3, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'also',
       level: 4,
       parent: [Object] },
     { type: 'strong', nesting: -1, level: 3, parent: [Object] },
     { type: 'emphasis', nesting: -1, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: ' put them into each other.',
       level: 2,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 1, parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 29,
  token: 
   { type: 'paragraph',
     nesting: -1,
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }