TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'paragraph', nesting: 1, level: 1, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'That\'s ',
       level: 2,
       parent: [Object] },
     { type: 'strong', nesting: 1, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'all',
       level: 3,
       parent: [Object] },
     { type: 'strong', nesting: -1, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: ' to say. ',
       level: 2,
       parent: [Object] },
     { type: 'emphasis', nesting: 1, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: '(Alex)',
       level: 3,
       parent: [Object] },
     { type: 'emphasis', nesting: -1, level: 2, parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 1, parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 11,
  token: 
   { type: 'paragraph',
     nesting: -1,
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }