TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'heading',
       nesting: 1,
       heading: 1,
       level: 1,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'heading 1',
       level: 2,
       parent: [Object] },
     { type: 'heading',
       nesting: -1,
       heading: 1,
       level: 1,
       parent: [Object] },
     { type: 'heading',
       nesting: 1,
       heading: 2,
       level: 1,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'heading 2',
       level: 2,
       parent: [Object] },
     { type: 'heading',
       nesting: -1,
       heading: 2,
       level: 1,
       parent: [Object] },
     { type: 'heading',
       nesting: 1,
       heading: 3,
       level: 1,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'heading 3',
       level: 2,
       parent: [Object] },
     { type: 'heading',
       nesting: -1,
       heading: 3,
       level: 1,
       parent: [Object] },
     { type: 'heading',
       nesting: 1,
       heading: 4,
       level: 1,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'heading 4',
       level: 2,
       parent: [Object] },
     { type: 'heading',
       nesting: -1,
       heading: 4,
       level: 1,
       parent: [Object] },
     { type: 'heading',
       nesting: 1,
       heading: 5,
       level: 1,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'heading 5',
       level: 2,
       parent: [Object] },
     { type: 'heading',
       nesting: -1,
       heading: 5,
       level: 1,
       parent: [Object] },
     { type: 'heading',
       nesting: 1,
       heading: 6,
       level: 1,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'heading 6',
       level: 2,
       parent: [Object] },
     { type: 'heading',
       nesting: -1,
       heading: 6,
       level: 1,
       parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 19,
  token: 
   { type: 'heading',
     nesting: -1,
     heading: 6,
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }