TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'table', nesting: 1, level: 1, parent: [Object] },
     { type: 'thead', nesting: 1, level: 2, parent: [Object] },
     { type: 'tr', nesting: 1, level: 3, parent: [Object] },
     { type: 'th',
       nesting: 1,
       align: 'left',
       level: 4,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Left-aligned',
       level: 5,
       parent: [Object] },
     { type: 'th', nesting: -1, level: 4, parent: [Object] },
     { type: 'th',
       nesting: 1,
       align: 'center',
       level: 4,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Center-aligned',
       level: 5,
       parent: [Object] },
     { type: 'th', nesting: -1, level: 4, parent: [Object] },
     { type: 'th',
       nesting: 1,
       align: 'right',
       level: 4,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Right-aligned',
       level: 5,
       parent: [Object] },
     { type: 'th', nesting: -1, level: 4, parent: [Object] },
     { type: 'tr', nesting: -1, level: 3, parent: [Object] },
     { type: 'thead', nesting: -1, level: 2, parent: [Object] },
     { type: 'tbody', nesting: 1, level: 2, parent: [Object] },
     { type: 'tr', nesting: 1, level: 3, parent: [Object] },
     { type: 'td', nesting: 1, level: 4, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: '1',
       level: 5,
       parent: [Object] },
     { type: 'td', nesting: -1, level: 4, parent: [Object] },
     { type: 'td', nesting: 1, level: 4, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'one',
       level: 5,
       parent: [Object] },
     { type: 'td', nesting: -1, level: 4, parent: [Object] },
     { type: 'td', nesting: 1, level: 4, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'eins',
       level: 5,
       parent: [Object] },
     { type: 'td', nesting: -1, level: 4, parent: [Object] },
     { type: 'tr', nesting: -1, level: 3, parent: [Object] },
     { type: 'tr', nesting: 1, level: 3, parent: [Object] },
     { type: 'td', nesting: 1, level: 4, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: '2',
       level: 5,
       parent: [Object] },
     { type: 'td', nesting: -1, level: 4, parent: [Object] },
     { type: 'td', nesting: 1, level: 4, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'two',
       level: 5,
       parent: [Object] },
     { type: 'td', nesting: -1, level: 4, parent: [Object] },
     { type: 'td', nesting: 1, level: 4, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'zwei',
       level: 5,
       parent: [Object] },
     { type: 'td', nesting: -1, level: 4, parent: [Object] },
     { type: 'tr', nesting: -1, level: 3, parent: [Object] },
     { type: 'tbody', nesting: -1, level: 2, parent: [Object] },
     { type: 'table', nesting: -1, level: 1, parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 40,
  token: 
   { type: 'table',
     nesting: -1,
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }