TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'container', nesting: 1, level: 1, parent: [Object] },
     { type: 'box',
       nesting: 1,
       box: 'ok',
       title: 'Ok',
       level: 2,
       parent: [Object] },
     { type: 'paragraph', nesting: 1, level: 3, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'This is a very long note to show how it will look in the different display',
       level: 4,
       parent: [Object] },
     { type: 'softbreak', nesting: 0, level: 4, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'modes which will show it minimized, maximized or with an scroll bar. It is',
       level: 4,
       parent: [Object] },
     { type: 'softbreak', nesting: 0, level: 4, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'shown in the minimized form at start but you may click it into scroll or',
       level: 4,
       parent: [Object] },
     { type: 'softbreak', nesting: 0, level: 4, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'maximized view as you like. In any other output which is not HTML it will',
       level: 4,
       parent: [Object] },
     { type: 'softbreak', nesting: 0, level: 4, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'always be displayed in full size (maximized). You may use the icons on the',
       level: 4,
       parent: [Object] },
     { type: 'softbreak', nesting: 0, level: 4, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'top left to change the appearance of this box if you want to minimize it,',
       level: 4,
       parent: [Object] },
     { type: 'softbreak', nesting: 0, level: 4, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'to open back in auto size (with possible scrollbars) or to maximize like',
       level: 4,
       parent: [Object] },
     { type: 'softbreak', nesting: 0, level: 4, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'in print view.',
       level: 4,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 3, parent: [Object] },
     { type: 'paragraph', nesting: 1, level: 3, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'This is a very long note to show how it will look in the different display',
       level: 4,
       parent: [Object] },
     { type: 'softbreak', nesting: 0, level: 4, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'modes which will show it minimized, maximized or with an scroll bar. It is',
       level: 4,
       parent: [Object] },
     { type: 'softbreak', nesting: 0, level: 4, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'shown in the minimized form at start but you may click it into scroll or',
       level: 4,
       parent: [Object] },
     { type: 'softbreak', nesting: 0, level: 4, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'maximized view as you like. In any other output which is not HTML it will',
       level: 4,
       parent: [Object] },
     { type: 'softbreak', nesting: 0, level: 4, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'always be displayed in full size (maximized). You may use the icons on the',
       level: 4,
       parent: [Object] },
     { type: 'softbreak', nesting: 0, level: 4, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'top left to change the appearance of this box if you want to minimize it,',
       level: 4,
       parent: [Object] },
     { type: 'softbreak', nesting: 0, level: 4, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'to open back in auto size (with possible scrollbars) or to maximize like',
       level: 4,
       parent: [Object] },
     { type: 'softbreak', nesting: 0, level: 4, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'in print view.',
       level: 4,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 3, parent: [Object] },
     { type: 'box', nesting: -1, level: 2, parent: [Object] },
     { type: 'container', nesting: -1, level: 1, parent: [Object] },
     { type: 'style',
       nesting: 0,
       format: 'html',
       block: true,
       content: 'container:size=min',
       level: 1,
       parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 40,
  token: 
   { type: 'style',
     nesting: 0,
     format: 'html',
     block: true,
     content: 'container:size=min',
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }