TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'container', nesting: 1, level: 1, parent: [Object] },
     { type: 'box',
       nesting: 1,
       box: 'detail',
       title: 'Detail',
       level: 2,
       parent: [Object] },
     { type: 'table', nesting: 1, level: 3, parent: [Object] },
     { type: 'thead', nesting: 1, level: 4, parent: [Object] },
     { type: 'tr', nesting: 1, level: 5, parent: [Object] },
     { type: 'th',
       nesting: 1,
       align: 'left',
       level: 6,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'ID',
       level: 7,
       parent: [Object] },
     { type: 'th', nesting: -1, level: 6, parent: [Object] },
     { type: 'th',
       nesting: 1,
       align: 'left',
       level: 6,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'English',
       level: 7,
       parent: [Object] },
     { type: 'th', nesting: -1, level: 6, parent: [Object] },
     { type: 'th',
       nesting: 1,
       align: 'left',
       level: 6,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'German',
       level: 7,
       parent: [Object] },
     { type: 'th', nesting: -1, level: 6, parent: [Object] },
     { type: 'tr', nesting: -1, level: 5, parent: [Object] },
     { type: 'thead', nesting: -1, level: 4, parent: [Object] },
     { type: 'tbody', nesting: 1, level: 4, parent: [Object] },
     { type: 'tr', nesting: 1, level: 5, parent: [Object] },
     { type: 'td', nesting: 1, level: 6, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: '1',
       level: 7,
       parent: [Object] },
     { type: 'td', nesting: -1, level: 6, parent: [Object] },
     { type: 'td', nesting: 1, level: 6, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'one',
       level: 7,
       parent: [Object] },
     { type: 'td', nesting: -1, level: 6, parent: [Object] },
     { type: 'td', nesting: 1, level: 6, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'eins',
       level: 7,
       parent: [Object] },
     { type: 'td', nesting: -1, level: 6, parent: [Object] },
     { type: 'tr', nesting: -1, level: 5, parent: [Object] },
     { type: 'tr', nesting: 1, level: 5, parent: [Object] },
     { type: 'td', nesting: 1, level: 6, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: '2',
       level: 7,
       parent: [Object] },
     { type: 'td', nesting: -1, level: 6, parent: [Object] },
     { type: 'td', nesting: 1, level: 6, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'two',
       level: 7,
       parent: [Object] },
     { type: 'td', nesting: -1, level: 6, parent: [Object] },
     { type: 'td', nesting: 1, level: 6, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'zwei',
       level: 7,
       parent: [Object] },
     { type: 'td', nesting: -1, level: 6, parent: [Object] },
     { type: 'tr', nesting: -1, level: 5, parent: [Object] },
     { type: 'tr', nesting: 1, level: 5, parent: [Object] },
     { type: 'td', nesting: 1, level: 6, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: '3',
       level: 7,
       parent: [Object] },
     { type: 'td', nesting: -1, level: 6, parent: [Object] },
     { type: 'td', nesting: 1, level: 6, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'three',
       level: 7,
       parent: [Object] },
     { type: 'td', nesting: -1, level: 6, parent: [Object] },
     { type: 'td', nesting: 1, level: 6, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'drei',
       level: 7,
       parent: [Object] },
     { type: 'td', nesting: -1, level: 6, parent: [Object] },
     { type: 'tr', nesting: -1, level: 5, parent: [Object] },
     { type: 'tr', nesting: 1, level: 5, parent: [Object] },
     { type: 'td', nesting: 1, level: 6, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: '12',
       level: 7,
       parent: [Object] },
     { type: 'td', nesting: -1, level: 6, parent: [Object] },
     { type: 'td', nesting: 1, level: 6, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'twelve',
       level: 7,
       parent: [Object] },
     { type: 'td', nesting: -1, level: 6, parent: [Object] },
     { type: 'td', nesting: 1, level: 6, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'zwölf',
       level: 7,
       parent: [Object] },
     { type: 'td', nesting: -1, level: 6, parent: [Object] },
     { type: 'tr', nesting: -1, level: 5, parent: [Object] },
     { type: 'tbody', nesting: -1, level: 4, parent: [Object] },
     { type: 'table', nesting: -1, level: 3, parent: [Object] },
     { type: 'box', nesting: -1, level: 2, parent: [Object] },
     { type: 'container', nesting: -1, level: 1, parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 66,
  token: 
   { type: 'container',
     nesting: -1,
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }