TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'paragraph', nesting: 1, level: 1, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Normal Text',
       level: 2,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 1, parent: [Object] },
     { type: 'blockquote', nesting: 1, level: 1, parent: [Object] },
     { type: 'paragraph', nesting: 1, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Level 1',
       level: 3,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 2, parent: [Object] },
     { type: 'blockquote', nesting: 1, level: 2, parent: [Object] },
     { type: 'paragraph', nesting: 1, level: 3, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Level 2',
       level: 4,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 3, parent: [Object] },
     { type: 'blockquote', nesting: 1, level: 3, parent: [Object] },
     { type: 'paragraph', nesting: 1, level: 4, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Level 3',
       level: 5,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 4, parent: [Object] },
     { type: 'blockquote', nesting: 1, level: 4, parent: [Object] },
     { type: 'paragraph', nesting: 1, level: 5, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Level 4',
       level: 6,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 5, parent: [Object] },
     { type: 'blockquote', nesting: 1, level: 5, parent: [Object] },
     { type: 'paragraph', nesting: 1, level: 6, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Level 5',
       level: 7,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 6, parent: [Object] },
     { type: 'blockquote', nesting: 1, level: 6, parent: [Object] },
     { type: 'paragraph', nesting: 1, level: 7, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Level 6',
       level: 8,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 7, parent: [Object] },
     { type: 'blockquote', nesting: 1, level: 7, parent: [Object] },
     { type: 'paragraph', nesting: 1, level: 8, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Level 7',
       level: 9,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 8, parent: [Object] },
     { type: 'blockquote', nesting: 1, level: 8, parent: [Object] },
     { type: 'paragraph', nesting: 1, level: 9, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Level 8',
       level: 10,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 9, parent: [Object] },
     { type: 'blockquote', nesting: -1, level: 8, parent: [Object] },
     { type: 'blockquote', nesting: -1, level: 7, parent: [Object] },
     { type: 'blockquote', nesting: -1, level: 6, parent: [Object] },
     { type: 'blockquote', nesting: -1, level: 5, parent: [Object] },
     { type: 'blockquote', nesting: -1, level: 4, parent: [Object] },
     { type: 'blockquote', nesting: -1, level: 3, parent: [Object] },
     { type: 'blockquote', nesting: -1, level: 2, parent: [Object] },
     { type: 'blockquote', nesting: -1, level: 1, parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 44,
  token: 
   { type: 'blockquote',
     nesting: -1,
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }