TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'blockquote', nesting: 1, level: 1, parent: [Object] },
     { type: 'paragraph', nesting: 1, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Manfred said:',
       level: 3,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 2, parent: [Object] },
     { type: 'blockquote', nesting: 1, level: 2, parent: [Object] },
     { type: 'paragraph', nesting: 1, level: 3, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Everything will work next week.',
       level: 4,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 3, parent: [Object] },
     { type: 'blockquote', nesting: -1, level: 2, parent: [Object] },
     { type: 'blockquote', nesting: -1, level: 1, parent: [Object] },
     { type: 'paragraph', nesting: 1, level: 1, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'But we don\'t think so.',
       level: 2,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 1, parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 14,
  token: 
   { type: 'paragraph',
     nesting: -1,
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }