TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'paragraph', nesting: 1, level: 1, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Solar System Exploration, 1950s – 1960s',
       level: 2,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 1, parent: [Object] },
     { type: 'list',
       nesting: 1,
       list: 'bullet',
       level: 1,
       parent: [Object] },
     { type: 'item',
       nesting: 1,
       task: false,
       level: 2,
       parent: [Object] },
     { type: 'paragraph',
       nesting: 1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Mercury',
       level: 4,
       parent: [Object] },
     { type: 'paragraph',
       nesting: -1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'item', nesting: -1, level: 2, parent: [Object] },
     { type: 'item',
       nesting: 1,
       task: true,
       level: 2,
       parent: [Object] },
     { type: 'paragraph',
       nesting: 1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Venus',
       level: 4,
       parent: [Object] },
     { type: 'paragraph',
       nesting: -1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'item', nesting: -1, level: 2, parent: [Object] },
     { type: 'item',
       nesting: 1,
       task: true,
       level: 2,
       parent: [Object] },
     { type: 'paragraph',
       nesting: 1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Earth (Orbit/Moon)',
       level: 4,
       parent: [Object] },
     { type: 'paragraph',
       nesting: -1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'item', nesting: -1, level: 2, parent: [Object] },
     { type: 'item',
       nesting: 1,
       task: true,
       level: 2,
       parent: [Object] },
     { type: 'paragraph',
       nesting: 1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Mars',
       level: 4,
       parent: [Object] },
     { type: 'paragraph',
       nesting: -1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'item', nesting: -1, level: 2, parent: [Object] },
     { type: 'item',
       nesting: 1,
       task: false,
       level: 2,
       parent: [Object] },
     { type: 'paragraph',
       nesting: 1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Jupiter',
       level: 4,
       parent: [Object] },
     { type: 'paragraph',
       nesting: -1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'item', nesting: -1, level: 2, parent: [Object] },
     { type: 'item',
       nesting: 1,
       task: false,
       level: 2,
       parent: [Object] },
     { type: 'paragraph',
       nesting: 1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Saturn',
       level: 4,
       parent: [Object] },
     { type: 'paragraph',
       nesting: -1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'item', nesting: -1, level: 2, parent: [Object] },
     { type: 'item',
       nesting: 1,
       task: false,
       level: 2,
       parent: [Object] },
     { type: 'paragraph',
       nesting: 1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Uranus',
       level: 4,
       parent: [Object] },
     { type: 'paragraph',
       nesting: -1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'item', nesting: -1, level: 2, parent: [Object] },
     { type: 'item',
       nesting: 1,
       task: false,
       level: 2,
       parent: [Object] },
     { type: 'paragraph',
       nesting: 1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Neptune',
       level: 4,
       parent: [Object] },
     { type: 'paragraph',
       nesting: -1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'item', nesting: -1, level: 2, parent: [Object] },
     { type: 'item',
       nesting: 1,
       task: false,
       level: 2,
       parent: [Object] },
     { type: 'paragraph',
       nesting: 1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Comet Haley',
       level: 4,
       parent: [Object] },
     { type: 'paragraph',
       nesting: -1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'item', nesting: -1, level: 2, parent: [Object] },
     { type: 'item', nesting: 1, level: 2, parent: [Object] },
     { type: 'paragraph',
       nesting: 1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'anything missing?',
       level: 4,
       parent: [Object] },
     { type: 'paragraph',
       nesting: -1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'item', nesting: -1, level: 2, parent: [Object] },
     { type: 'list',
       nesting: -1,
       list: 'bullet',
       level: 1,
       parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 56,
  token: 
   { type: 'list',
     nesting: -1,
     list: 'bullet',
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }