TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'dl', nesting: 1, level: 1, parent: [Object] },
     { type: 'dt', nesting: 1, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Term 1',
       level: 3,
       parent: [Object] },
     { type: 'dt', nesting: -1, level: 2, parent: [Object] },
     { type: 'dd', nesting: 1, level: 2, parent: [Object] },
     { type: 'paragraph',
       nesting: 1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Definition 1',
       level: 4,
       parent: [Object] },
     { type: 'paragraph',
       nesting: -1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'dd', nesting: -1, level: 2, parent: [Object] },
     { type: 'dt', nesting: 1, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Term 2',
       level: 3,
       parent: [Object] },
     { type: 'dt', nesting: -1, level: 2, parent: [Object] },
     { type: 'dd', nesting: 1, level: 2, parent: [Object] },
     { type: 'paragraph',
       nesting: 1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Definition 2',
       level: 4,
       parent: [Object] },
     { type: 'paragraph',
       nesting: -1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'dd', nesting: -1, level: 2, parent: [Object] },
     { type: 'dl', nesting: -1, level: 1, parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 19,
  token: 
   { type: 'dl',
     nesting: -1,
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }