TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'list',
       nesting: 1,
       list: 'bullet',
       level: 1,
       parent: [Object] },
     { type: 'item', nesting: 1, level: 2, parent: [Object] },
     { type: 'paragraph',
       nesting: 1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'search the internet sites for a cheap holiday trip to an all inclusive hotel near the beach in the south of spain',
       level: 4,
       parent: [Object] },
     { type: 'paragraph',
       nesting: -1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'item', nesting: -1, level: 2, parent: [Object] },
     { type: 'item', nesting: 1, level: 2, parent: [Object] },
     { type: 'paragraph',
       nesting: 1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'have some fun and relax within your two weeks in spain to be back at work afterwords with fresh energy',
       level: 4,
       parent: [Object] },
     { type: 'paragraph',
       nesting: -1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'item', nesting: -1, level: 2, parent: [Object] },
     { type: 'list',
       nesting: -1,
       list: 'bullet',
       level: 1,
       parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 13,
  token: 
   { type: 'list',
     nesting: -1,
     list: 'bullet',
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }