TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'paragraph', nesting: 1, level: 1, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Capital Cities:',
       level: 2,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 1, parent: [Object] },
     { type: 'list',
       nesting: 1,
       list: 'ordered',
       start: 1,
       level: 1,
       parent: [Object] },
     { type: 'item', nesting: 1, level: 2, parent: [Object] },
     { type: 'paragraph',
       nesting: 1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Europe',
       level: 4,
       parent: [Object] },
     { type: 'paragraph',
       nesting: -1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'list',
       nesting: 1,
       list: 'bullet',
       level: 3,
       parent: [Object] },
     { type: 'item', nesting: 1, level: 4, parent: [Object] },
     { type: 'paragraph',
       nesting: 1,
       hidden: true,
       level: 5,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'London',
       level: 6,
       parent: [Object] },
     { type: 'paragraph',
       nesting: -1,
       hidden: true,
       level: 5,
       parent: [Object] },
     { type: 'item', nesting: -1, level: 4, parent: [Object] },
     { type: 'item', nesting: 1, level: 4, parent: [Object] },
     { type: 'paragraph',
       nesting: 1,
       hidden: true,
       level: 5,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Berlin',
       level: 6,
       parent: [Object] },
     { type: 'paragraph',
       nesting: -1,
       hidden: true,
       level: 5,
       parent: [Object] },
     { type: 'item', nesting: -1, level: 4, parent: [Object] },
     { type: 'item', nesting: 1, level: 4, parent: [Object] },
     { type: 'paragraph',
       nesting: 1,
       hidden: true,
       level: 5,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Paris',
       level: 6,
       parent: [Object] },
     { type: 'paragraph',
       nesting: -1,
       hidden: true,
       level: 5,
       parent: [Object] },
     { type: 'item', nesting: -1, level: 4, parent: [Object] },
     { type: 'list',
       nesting: -1,
       list: 'bullet',
       level: 3,
       parent: [Object] },
     { type: 'item', nesting: -1, level: 2, parent: [Object] },
     { type: 'item', nesting: 1, level: 2, parent: [Object] },
     { type: 'paragraph',
       nesting: 1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Africa',
       level: 4,
       parent: [Object] },
     { type: 'paragraph',
       nesting: -1,
       hidden: true,
       level: 3,
       parent: [Object] },
     { type: 'list',
       nesting: 1,
       list: 'bullet',
       level: 3,
       parent: [Object] },
     { type: 'item', nesting: 1, level: 4, parent: [Object] },
     { type: 'paragraph',
       nesting: 1,
       hidden: true,
       level: 5,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Kairo',
       level: 6,
       parent: [Object] },
     { type: 'paragraph',
       nesting: -1,
       hidden: true,
       level: 5,
       parent: [Object] },
     { type: 'item', nesting: -1, level: 4, parent: [Object] },
     { type: 'item', nesting: 1, level: 4, parent: [Object] },
     { type: 'paragraph',
       nesting: 1,
       hidden: true,
       level: 5,
       parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'Tunis',
       level: 6,
       parent: [Object] },
     { type: 'paragraph',
       nesting: -1,
       hidden: true,
       level: 5,
       parent: [Object] },
     { type: 'item', nesting: -1, level: 4, parent: [Object] },
     { type: 'list',
       nesting: -1,
       list: 'bullet',
       level: 3,
       parent: [Object] },
     { type: 'item', nesting: -1, level: 2, parent: [Object] },
     { type: 'list',
       nesting: -1,
       list: 'ordered',
       start: 1,
       level: 1,
       parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 45,
  token: 
   { type: 'list',
     nesting: -1,
     list: 'ordered',
     start: 1,
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }