TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'code',
       nesting: 1,
       language: 'csharp',
       level: 1,
       parent: [Object] },
     { type: 'text',
       content: 'using System;\n\n#pragma warning disable 414, 3021\n\n/// <summary>Main task</summary>\nasync Task<int, int> AccessTheWebAsync()\n{\n    Console.WriteLine("Hello, World!");\n    string urlContents = await getStringTask;\n    return urlContents.Length;\n}',
       level: 2,
       parent: [Object] },
     { type: 'code',
       nesting: -1,
       language: 'csharp',
       level: 1,
       parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 4,
  token: 
   { type: 'code',
     nesting: -1,
     language: 'csharp',
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }