TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'code',
       nesting: 1,
       language: 'html',
       level: 1,
       parent: [Object] },
     { type: 'text',
       content: '<!DOCTYPE html>\n<title>Title</title>\n\n<style>body {width: 500px;}</style>\n\n<script type="application/javascript">\n  function $init() {return true;}\n</script>\n\n<body>\n  <p checked class="title" id=\'title\'>Title</p>\n  <!-- here goes the rest of the page -->\n</body>',
       level: 2,
       parent: [Object] },
     { type: 'code',
       nesting: -1,
       language: 'html',
       level: 1,
       parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 4,
  token: 
   { type: 'code',
     nesting: -1,
     language: 'html',
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }