TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'code',
       nesting: 1,
       language: 'javascript',
       level: 1,
       parent: [Object] },
     { type: 'text',
       content: 'function $initHighlight(block, cls) {\n  try {\n    if (cls.search(/\\bno-highlight\\b/) != -1)\n      return process(block, true, 0x0F) +\n             ` class="${cls}"`;\n  } catch (e) {\n    /* handle exception */\n  }\n  for (var i = 0 / 2; i < classes.length; i++) {\n    if (checkCondition(classes[i]) === undefined)\n      console.log(\'undefined\');\n  }\n}\n\nexport  $initHighlight;',
       level: 2,
       parent: [Object] },
     { type: 'code',
       nesting: -1,
       language: 'javascript',
       level: 1,
       parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 4,
  token: 
   { type: 'code',
     nesting: -1,
     language: 'javascript',
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }