TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'code',
       nesting: 1,
       language: 'tex',
       level: 1,
       parent: [Object] },
     { type: 'text',
       content: '\\documentclass{article}\n\\usepackage[koi8-r]{inputenc}\n\\hoffset=0pt\n\\voffset=.3em\n\\tolerance=400\n\\newcommand{\\eTiX}{\\TeX}\n\\begin{document}\n\\section*{Highlight.js}\n\\begin{table}[c|c]\n$\\frac 12\\, + \\, \\frac 1{x^3}\\text{Hello \\! world}$ & \\textbf{Goodbye\\~ world} \\\\\\eTiX $ \\pi=400 $\n\\end{table}\nCh\\\'erie, \\c{c}a ne me pla\\^\\i t pas! % comment \\b\nG\\"otterd\\"ammerung~45\\%=34.\n$$\n    \\int\\limits_{0}^{\\pi}\\frac{4}{x-7}=3\n$$\n\\end{document}',
       level: 2,
       parent: [Object] },
     { type: 'code',
       nesting: -1,
       language: 'tex',
       level: 1,
       parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 4,
  token: 
   { type: 'code',
     nesting: -1,
     language: 'tex',
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }