TokenList {
  data: 
   [ { type: 'document', nesting: 1, level: 0 },
     { type: 'paragraph', nesting: 1, level: 1, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'You need H',
       level: 2,
       parent: [Object] },
     { type: 'subscript', nesting: 1, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: '2',
       level: 3,
       parent: [Object] },
     { type: 'subscript', nesting: -1, level: 2, parent: [Object] },
     { type: 'text',
       nesting: 0,
       content: 'O for this experiment.',
       level: 2,
       parent: [Object] },
     { type: 'paragraph', nesting: -1, level: 1, parent: [Object] },
     { type: 'document', nesting: -1, level: 0 } ],
  pos: 8,
  token: 
   { type: 'paragraph',
     nesting: -1,
     level: 1,
     parent: { type: 'document', nesting: 1, level: 0 } } }